# Generated by Django 5.0.2 on 2024-02-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_hostel_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_mess_member',
            field=models.BooleanField(default=True),
        ),
    ]
